baseURL = 'https://dmpk.xyz'
languageCode = 'en-us'
title = 'Dominik Pakuła'
theme = 'simple-hugo'

disableKinds = ['taxonomy', 'term']

[params]
    footerText = "Built with <a href='http://gohugo.io' target='_blank' rel='noopener noreferrer'>Hugo</a>"

[menu]

    [[menu.main]]
        name = 'Blog'
        pageRef = '/blog'
        weight = 1

    [[menu.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 2

    [[menu.footer]]
        name = "RSS"
        url = 'https://dmpk.xyz/index.xml'
        weight = 2
        [[menu.footer.params]]
            path = 'static/logos/rss.svg'

    [[menu.footer]]
        name = 'Github'
        url = 'https://github.com/D00NIK/'
        weight = 1
        [[menu.footer.params]]
          path = 'static/logos/github.svg'

    [[menu.footer]]
        name = "LinkedIn"
        url = 'https://www.linkedin.com/in/dominikpakula/'
        weight = 2
        [[menu.footer.params]]
            path = 'static/logos/linkedin.svg'


[markup]
    [markup.goldmark.parser]
        wrapStandAloneImageWithinParagraph = false
